DELETE http://localhost:3001/api/blogs/8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImprdWthbmVuIiwiaWQiOjEsImlhdCI6MTc0NDI3NTY1OH0.q6hEiSjAeoBmns4Y41F54PhGsEir0lQiSKFqmlCxesY